defaults:
  - _self_
  - dataset: cola
  - peft: fine_tune

model_name: state-spaces/mamba-130m-hf

wandb:
  project: new_glue

training:
  batch_size: 128
  epochs: 50
  lr: 0.00005
  weight_decay: 0.00001
  warmup_steps: 500
  optim: adamw_torch_fused
  lr_scheduler_type: cosine

output_dir_template: "lmclass_{dataset_name}_{peft}_{epochs}ep_{lr}"
checkpoints: './checkpoints'
save_dir: './models'
